### PR TITLE
Time stepping

### PR DESCRIPTION
**Pull request by zachhardy**
Time-stepping implemented within the radpydro class.

Here comes a bunch of information about changes...

1) Added final time (Tf) member variable to inputs. Added time timeStep_num member variables to radpydro for tracking. Added run function to radpydro which performs time steps until the final time is reached.

2) Added plotFields function in fields class. This currently plots on a giant subplot. 

4) Changed a + to a - in the dE_k computation of computeTimeStep in radpydro. This is for a derivative, it should be a - not a +.

5) Conservation function is only good for one time step (the term that is a sum over time steps is not yet implemented). I suggest we add the additional member variables kinetice_energy, internal_energy, radiation_energy, radiation_energy_leakage and track through the simulation as necessary to compute conservation.

### CODE REVIEW

**Comment by zachhardy** [comment]
Additionally, we need to get an easy implementation for a hydro only solve.

**Comment by grmnptr** [comment]
Setting everything rad related to 0?

**Comment by grmnptr** [comment]
Plus not solving the rad equations.

**Comment by zachhardy** [comment]
Yea, gotta fix the bug with zero rad BCs. I was just thinking it may be useful to give it a true/false and it do all of that for you automatically. Easy change.

**Comment by zachhardy** [comment]
It's actually a less trivial change than I thought, I think, because we have to turn off emission as well.  Setting radiation to 0 won't do the trick completely.

**Comment by zachhardy** [comment]
Finished up the hydro only calculation changes and got rid of dt as a parameter for every function associated with the solve. It is now queried in each function that used to call it.

**Comment by zachhardy** [comment]
Energy conservation in each time step and shock solutions obtained for hydro only. Something is broken in radiation part.

**Review by loganharbour — APPROVED** [review]

**Pull request merged**
