### PR TITLE
Radshock

### PR DESCRIPTION
**Pull request by zachhardy**
This branch uses the code from Peter's branch with minor updates to solve the benchmark problem on eCampus. The result matches the correct result.

### CODE REVIEW

**Comment by loganharbour** [comment]
@zachhardy stop working on this

**Comment by zachhardy** [comment]
Lol, no matter what I do it's wrong :)

*Zachary Hardy '18*
–––––––––––––––––––––––––––––––––––––––––––

*Texas A&M University*
*B.S. Nuclear Engineering*
–––––––––––––––––––––––––––––––––––––––––––
–––––––––––––––––––––––––––––––––––––––––––
Cell:                    (682) 667-3646
School Email:     zach.hardy@tamu.edu
Personal Email:  zhardy1115@gmail.com

--

**Comment by loganharbour** [comment]
Not true. it's mostly right :-)

**Comment by loganharbour** [comment]
Closed due to #22

**Pull request closed without merging**
